name: Coverage

on: [ push, pull_request ]

jobs:
  run:
    name: Coverage

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --dev --prefer-dist --no-progress --no-suggest

    - name: Run Coverage
      run: composer run-script coverage

    - uses: codecov/codecov-action@v2
      with:
        files: build/logs/clover.xml
