name: Coverage

on: [ push, pull_request ]

jobs:
  run:
    name: Coverage

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Coverage
      run: composer run-script coverage

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: build/logs/clover.xml
